package me.unidok.random

import androidx.compose.foundation.layout.*
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import java.util.*

@Composable
fun RandomUUIDGenerator() {
    var generated by remember { mutableStateOf<String?>(null) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        ResultField(
            result = generated?.let { "UUID: $it" },
            onClear = { generated = null }
        )

        Spacer(modifier = Modifier.height(30.dp))

        Button(
            onClick = { generated = UUID.randomUUID().toString() }
        ) {
            Text("Сгенерировать случайный UUID")
        }
    }
}